version: '3.9'

services:
  postgres:
    build: ../postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=kayrosteam
      - POSTGRES_PASSWORD=resto123
      - POSTGRES_DB=main_db
    volumes:
      - ../postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio/data:/data
    environment:
      - MINIO_ROOT_USER=kayrosteam
      - MINIO_ROOT_PASSWORD=resto123
    command: server --console-address :9001 /data
  backend:
    build: ../../
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
      - minio
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/logs:/var/log/nginx/
      - ../nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      # here you need to place the path of frontend static folder
      - /Users/ivanlobanov/Programming/2024_Kayros_Frontend/dist:/var/www/dist
    ports:
      - "80:80"
    depends_on:
      - backend