version: '3.9'

services:
  postgres:
    build: ../postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=kayrosteam
      - POSTGRES_PASSWORD=resto123
      - POSTGRES_DB=main_db
    volumes:
      - ../postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/ivanlobanov/Programming/2024_Kayros_Frontend/dist:/var/www/dist
    ports:
      - "80:80"
    depends_on:
      - minio
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio/data:/data
    environment:
      - MINIO_ROOT_USER=kayrosteam
      - MINIO_ROOT_PASSWORD=resto123
    command: server /data --console-address ":9001"

