global:
  scrape_interval:     30s
  evaluation_interval: 10s

scrape_configs:
# microservices
  - job_name: 'gateway'
    static_configs:
    - targets: ['gateway:8000']

  - job_name: 'rest-grpc'
    static_configs:
    - targets: ['rest-grpc:8081']

  - job_name: 'auth-grpc'
    static_configs:
    - targets: ['auth-grpc:8082']

  - job_name: 'user-grpc'
    static_configs:
    - targets: ['user-grpc:8084']

  - job_name: 'session-grpc'
    static_configs:
    - targets: ['session-grpc:8085']

  - job_name: 'comment-grpc'
    static_configs:
    - targets: ['comment-grpc:8083']

# prometheus units
  - job_name: 'node-exporter'
    static_configs:
    - targets: [ 'node-exporter:9100' ]
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

