server:
    write-timeout: 5
    read-timeout: 5
    idle-timeout: 20
    shutdown-duration: 5
    host: "localhost"
    port: 8000

postgres:
    host: "localhost"
    port: 5432
    user: 'admin'
    password: '123'
    database: 'main_db'
    sslmode: 'disable'

minio:
    port-server: 9001
    console-server: 9000
    secret-key: 'minio'
    access-key: '123'

redis:
    port: 6379
