global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'system'
    static_configs:
    - targets: ['localhost:9100']

rule_files:

alerting:

