version: '3.9'

services:
  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=restoadmin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=main_db
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf




